### PR TITLE
Remove curietasker completely

### LINKED ISSUE #725: Curietasker docker image has missing python package
**Describe the bug**
Curietasker image (curiefense/curietasker:main) has missing python package.
https://hub.docker.com/layers/curiefense/curietasker/main/images/sha256-72b5975502f208d93643ea0059d161cb8f8ae3b4be92aa9de89238f35e451d1f?context=explore

docker logs curietasker

`Determining whether the tasks namespace should be created...
The tasks namespace already exists.
Traceback (most recent call last):
  File "/usr/local/bin/curietasker", line 3, in <module>
    from curietasker import main
  File "/usr/local/lib/python3.7/dist-packages/curietasker/__init__.py", line 7, in <module>
    from . import tasker
  File "/usr/local/lib/python3.7/dist-packages/curietasker/tasker.py", line 7, in <module>
    from . import tasks_list_updates
  File "/usr/local/lib/python3.7/dist-packages/curietasker/tasks_list_updates.py", line 7, in <module>
    from jsonschema import validate, ValidationError
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/usr/local/lib/python3.7/dist-packages/jsonschema/_types.py", line 6, in <module>
    from pyrsistent import pmap
ModuleNotFoundError: No module named 'pyrsistent'`

**To Reproduce**
docker-compose -f compose/docker-compose.yaml
docker logs curietasker

**Expected behavior**
Old image (curiefense/curietasker:latest) working fine.

Docker version 20.10.12, build e91ed57

### PR DESCRIPTION
**Pull request by xavier-rbz**
Curietasker is not used for any purpose, and the current images does not
work because of an incorrect Python environment.

Fixes #725.

Signed-off-by: Xavier <xavier@reblaze.com>

### CODE REVIEW

**Comment by xavier-rbz** [comment]
E2E tests on minikube are expected to fail because the corresponding [PR](https://github.com/curiefense/curiefense-helm/pull/25) in curiefense-helm has not been approved or merged yet. Let's re-run CI here after it has been merged, and the charts index has been updated.

**Review by tzuryby — APPROVED** [review]

**Review by tzuryby — APPROVED** [review]

**Comment by xavier-rbz** [comment]
* https://github.com/curiefense/curiefense-helm/pull/25 is now merged
* [Release 1.5.2](https://github.com/curiefense/curiefense-helm/releases/tag/curiefense-1.5.2) of the charts has been created
* Charts index has been [updated](https://github.com/curiefense/curiefense-helm/commit/a8aba68b0983286764994637ed539f61d24d9d06)
=> Re-running CI, expecting everything to be green.

**Comment by xavier-rbz** [comment]
PR rebased following a conflict with recently-merged https://github.com/curiefense/curiefense/pull/809

**Review by bartavelle — APPROVED** [review]
LGTM

**Pull request merged**
