### PR TITLE
Newlog

### PR DESCRIPTION
**Pull request by bartavelle**
This PR contains:

 * external processing patch
 * response code capture
 * new log format (documented in the LOGS.md file)
 * stability updates
 * new fuzzing code
 * using tags in tag rules
 * new autotags
 * make the request_header action work properly
 * special handling for the referer
 * templating for request_header
 * Python bindings
 * response code hooking (the actual response code is stored, only works for envoy)
 * change in decoded parameter names

# External processing

The system exists with images, but is disabled as it is alpha quality.

# Request headers action
The action has the following format in configuration:

```json
{
  "type": "request_header",
  "params": {
     "headers": { "header-name": "content" }
  }
}
```
It adds headers to the original request and forwards the message to the upstream server. *this is a final action*

# Content type for custom responses

```json
{
   "type": "response",
   "params": {
      "content_type": "application/json",
      "status": "200",
      "content": "{}"
   }
}
```

# Referer string handling

In the content filter definition, there is a new parameter `referer_as_uri`, defaults to `false`. When set to `true`, it will parse the content of the `Referer` header, and adds path parts and query parameters to the list of parameters, prefixed with `ref:`.

The masking system should work properly with the referer header.

# all/path sections in content filter

New sections in content filter:
 * path: applies on path elements
 * all: applies on all sections, before the specific section

# Templating

When the `headers` parameter is set to an action, its content can contain variables. For example:

```json
{
  "type": "request_header",
  "params": {
     "headers": { "header-name": "${ip} - ${arguments.dd}" }
  }
}
```

Variables are introduced with `${...}`, and can be the following:

* `headers.xx`
* `cookies.xx`
* `args.xx` or `arguments.xx`
* `attrs.xx` or `attributes.xx`
* `ip`
* `path`
* `query`
* `uri`
* `country`
* `method`
* `asn`
* `company`
* `authority`
* `tags`

Variables can be escaped with back slashes: `${args.non_escaped} \${args.escaped}`. In this example, this will be rendered as `nil ${args.escaped}`. Strings that do not resolve as query selectors (for example `${a.b.c}`) will he rendered without substitution.

# change in decoded parameter names

The decoded parameters now overwrite the encoded version, unless the decoding filter was base64, in which case a new parameter (with the original name suffixed by `:decoded` is created).

### CODE REVIEW

**Review by tzuryby — DISMISSED** [review]

**Comment by tzuryby** [comment]
few issues:

a) e2e is failing. perhaps easy to fix.
b) see below, 403 is presented as response status while none is active, and matter of fact, 200 was the actual return value:


```
{
  "_index": "curieaccesslog-2022.07.10-000001",
  "_type": "_doc",
  "_id": "biME54EB5CT1EjpIankJ",
  "_version": 1,
  "_score": null,
  "fields": {
    "agent.version.keyword": [
      "7.13.3"
    ],
    "host.name.keyword": [
      "curieproxy"
    ],
    "agent.hostname.keyword": [
      "curieproxy"
    ],
    "ecs.version.keyword": [
      "1.8.0"
    ],
    "content_filter_triggers": [
      {
        "risk_level": [
          5
        ],
        "section.keyword": [
          "uri"
        ],
        "ruleid.keyword": [
          "600110"
        ],
        "type.keyword": [
          "signature"
        ],
        "value.keyword": [
          ")))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))<<<<"
        ],
        "name": [
          "amp;rss"
        ],
        "active": [
          true
        ],
        "name.keyword": [
          "amp;rss"
        ],
        "section": [
          "uri"
        ],
        "type": [
          "signature"
        ],
        "ruleid": [
          "600110"
        ],
        "value": [
          ")))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))<<<<"
        ]
      }
    ],
    "trigger_counters.acl": [
      0
    ],
    "security_config.revision": [
      "18d1e84fd34c109e89d22365c7084f14a9ed358f"
    ],
    "agent.name": [
      "curieproxy"
    ],
    "processing_stage": [
      6
    ],
    "trigger_counters.content_filters": [
      1
    ],
    "host.name": [
      "curieproxy"
    ],
    "logs": [
      "D 0µs Inspection init",
      "D 23µs Inspection starts (grasshopper active: true)",
      "D 52µs CFGLOAD logs start",
      "D 1663344µs Loaded profile __default__ with 188 rules",
      "D 53µs CFGLOAD logs end",
      "D 55µs Selected hostmap default entry",
      "D 55µs Selected hostmap entry default",
      "D 60µs map_request starts",
      "D 82µs headers mapped",
      "D 138µs geoip computed",
      "D 150µs uri parsed",
      "D 150µs body parsed",
      "D 150µs args mapped",
      "W 156µs Could not find rbzid cookie!",
      "D 186µs request tagged",
      "D 191µs challenge phase2 ignored",
      "D 193µs flow checks done",
      "D 193µs no limits to check",
      "D 194µs limit checks done (0 limits)",
      "D 195µs ACL result: Match { bot: None, human: None }",
      "D 519µs matching content filter signatures: true",
      "D 539µs signature matched [0..8] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 558µs signature matched [0..9] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 566µs signature matched [0..10] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 572µs signature matched [0..11] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 577µs signature matched [0..12] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 582µs signature matched [0..13] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 587µs signature matched [0..14] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 593µs signature matched [0..15] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 598µs signature matched [0..16] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 603µs signature matched [0..17] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 608µs signature matched [0..18] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 613µs signature matched [0..19] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 619µs signature matched [0..20] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 624µs signature matched [0..21] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 629µs signature matched [0..22] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 634µs signature matched [0..23] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 639µs signature matched [0..24] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 647µs signature matched [0..25] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 653µs signature matched [0..26] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 658µs signature matched [0..27] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 663µs signature matched [0..28] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 668µs signature matched [0..29] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 673µs signature matched [0..30] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 678µs signature matched [0..31] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 683µs signature matched [0..32] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 688µs signature matched [0..33] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 705µs signature matched [0..34] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 710µs signature matched [0..35] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 715µs signature matched [0..36] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 720µs signature matched [0..37] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 726µs signature matched [0..38] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 731µs signature matched [0..39] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 736µs signature matched [0..40] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 741µs signature matched [0..41] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 746µs signature matched [0..42] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 751µs signature matched [0..43] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 756µs signature matched [0..44] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 761µs signature matched [0..45] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 766µs signature matched [0..46] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 771µs signature matched [0..47] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 776µs signature matched [0..48] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 781µs signature matched [0..49] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 786µs signature matched [0..50] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 791µs signature matched [0..51] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 797µs signature matched [0..52] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 802µs signature matched [0..53] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 806µs signature matched [0..54] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 812µs signature matched [0..55] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 817µs signature matched [0..56] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 822µs signature matched [0..57] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 826µs signature matched [0..58] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 831µs signature matched [0..59] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 836µs signature matched [0..60] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 841µs signature matched [0..61] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 846µs signature matched [0..62] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 863µs signature matched [0..63] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 868µs signature matched [0..64] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 873µs signature matched [0..65] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 878µs signature matched [0..66] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 883µs signature matched [0..67] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 888µs signature matched [0..68] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 893µs signature matched [0..69] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 898µs signature matched [0..70] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 902µs signature matched [0..71] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 907µs signature matched [0..72] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 912µs signature matched [0..73] ContentFilterRule { id: \"600110\", operand: \"([$@{}()\\\\[\\\\]].*){8,}\", risk: 5, category: \"generic\", subcategory: \"generic\", tags: {} }",
      "D 934µs Content Filter checks done"
    ],
    "security_config.global_filters_active": [
      1
    ],
    "method": [
      "GET"
    ],
    "ip": [
      "199.203.196.185"
    ],
    "agent.id.keyword": [
      "3a76f923-9c40-45fd-b82f-e4f635cd1a0c"
    ],
    "trigger_counters.flow_control": [
      0
    ],
    "input.type": [
      "stdin"
    ],
    "log.offset": [
      0
    ],
    "agent.hostname": [
      "curieproxy"
    ],
    "tags": [
      "bot",
      "contentfiltername:default-contentfilter",
      "all",
      "securitypolicy:default-entry",
      "geo-continent-name:asia",
      "geo-org:cellcom-fixed-line-communication-l-p-",
      "geo-region:central-district",
      "cf-rule-subcategory:generic",
      "aclname:default-acl",
      "cookies:0",
      "geo-asn:1680",
      "cf-rule-id:600110",
      "geo-continent-code:as",
      "geo-country:israel",
      "ip:199-203-196-185",
      "args:2",
      "contentfilterid:--default--",
      "cf-rule-risk:5",
      "geo-city:peta--tiqwa",
      "aclid:--default--",
      "cf-rule-category:generic",
      "headers:11",
      "geo-subregion:nil",
      "host:34-65-172-31:30081",
      "securitypolicy-entry:default"
    ],
    "trigger_counters.rate_limit_active": [
      0
    ],
    "agent.id": [
      "3a76f923-9c40-45fd-b82f-e4f635cd1a0c"
    ],
    "ecs.version": [
      "1.8.0"
    ],
    "authority": [
      "34.65.172.31:30081"
    ],
    "agent.version": [
      "7.13.3"
    ],
    "trigger_counters.global_filters": [
      0
    ],
    "trigger_counters.global_filters_active": [
      0
    ],
    "response_code": [
      403
    ],
    "input.type.keyword": [
      "stdin"
    ],
    "security_config.acl_active": [
      false
    ],
    "security_config.cf_rules": [
      188
    ],
    "cookies": [
      {}
    ],
    "agent.type": [
      "filebeat"
    ],
    "path_parts": [
      {
        "part3": "blog",
        "path": "/limit//blog",
        "part3:decoded": "nZ ",
        "part1": "limit"
      }
    ],
    "proxy.location": [
      {
        "coordinates": [
          32.0876,
          34.8739
        ],
        "type": "Point"
      }
    ],
    "trigger_counters.rate_limit": [
      0
    ],
    "trigger_counters.flow_control_active": [
      0
    ],
    "log.file.path.keyword": [
      ""
    ],
    "agent.type.keyword": [
      "filebeat"
    ],
    "timestamp": [
      "2022-07-10T07:30:34.140772027Z"
    ],
    "agent.ephemeral_id.keyword": [
      "f85e3691-4d39-4a57-91ab-bee9619ddfec"
    ],
    "headers": [
      {
        "x-request-id": "5a986e1c-6f97-412e-8842-247e8d0de236",
        "x-envoy-external-address": "199.203.196.185",
        "accept-language": "en-US,en;q=0.9,he-IL;q=0.8,he;q=0.7,ar;q=0.6",
        "x-forwarded-proto": "http",
        "upgrade-insecure-requests": "1",
        "x-forwarded-for": "199.203.196.185",
        "dnt": "1",
        "accept-encoding": "gzip, deflate",
        "accept:decoded": "text/html,application/xhtml xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36",
        "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      }
    ],
    "agent.name.keyword": [
      "curieproxy"
    ],
    "trigger_counters.content_filters_active": [
      0
    ],
    "uri": [
      "/limit//blog?page=11&amp;rss=)))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))%3C%3C%3C%3C"
    ],
    "security_config.cf_active": [
      false
    ],
    "@timestamp": [
      "2022-07-10T07:30:34.145Z"
    ],
    "trigger_counters.acl_active": [
      0
    ],
    "log.file.path": [
      ""
    ],
    "security_config.rate_limit_rules": [
      0
    ],
    "agent.ephemeral_id": [
      "f85e3691-4d39-4a57-91ab-bee9619ddfec"
    ],
    "arguments": [
      {
        "amp;rss": ")))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))<<<<",
        "page": "11"
      }
    ]
  },
  "sort": [
    1657438234140772000
  ]
}
```

**Comment by xavier-rbz** [comment]
Logs are now output by envoy to stdout, whereas they used to be sent to curielogger over GRPC.

In docker-compose deployments, envoy's stdout is captured by a filebeat instance that runs in the curieproxy-envoy container.

*In my opinion*, filebeat should not be running in that container. It should run in another container, as is done in <https://github.com/cosminseceleanu/tutorials/blob/master/docker-logs-elk/docker-compose.yml#L9>. I plan on integrating that to the newlog branch.

* [ ] Remove filebeat from the curieproxy-envoy container, move it to a separate container

In k8s deployments, envoy's stdout cannot be captured. We want to make things simple for (1) customers who already have their own log collection mechanisms, while ensuring that logging works out of the box for others (2). We may choose to support several implementations:

1. envoy logs to stdout, customers manage forwarding logs to ES/Kibana, and defining the index template. This supports use case (1).
2. envoy may log to stdout but also sends logs over GRPC to curielogger, which outputs them to its stdout, which is read by filebeat, which sends them to ES (as is currently done). This supports use case (2), and also supports planned metrics aggregation changes.
3. envoy logs to stdout, which is redirected to a local file, and read by filebeat running in a sidecar. This supports use case (2), but requires running a filebeat sidecar. Seems worse than option 2.
4. envoy logs to stdout; we provide a mechanism to collect the cluster logs, and forward them to ES. This typically means running a DaemonSet where filebeat interfaces the k8s API, and reads envoy logs from `/var/log/containers/` (which is not part of the k8s API...).

My choice for k8s deployments would be implementing 1. and 2. This means:
* [ ] For users who handle collecting logs themselves, document the fact that they must define an index template
* [ ] curielogger should output full logs (in `newlog`, the path is currently absent, which is why the e2e log fails)
* [ ] the charts in curiefense-helm must be updated to support choosing between 1. and 2.

Thoughts?

**Comment by bartavelle** [comment]
> few issues:
> 
> a) e2e is failing. perhaps easy to fix.

The failing case is related to logging in the K8 environment. This indeed needs to be solved.

> b) see below, 403 is presented as response status while none is active, and matter of fact, 200 was the actual return value:

The actual response code is not captured in the Lua code when the request is accepted. This is the code you would have gotten if content filters were active. This needs to be properly documented to avoid confusion.

> c) under log, there are repeatitive lines (see the id:600110) which may suggest we can reduce processing time?

Outside of logging, these duplication are taken care of. If you raise the log level, they won't appear anymore. Should deduplication also happen in logging?

**Comment by tzuryby** [comment]
> > b) see below, 403 is presented as response status while none is active, and matter of fact, 200 was the actual return value:
> 
> The actual response code is not captured in the Lua code when the request is accepted. This is the code you would have gotten if content filters were active. This needs to be properly documented to avoid confusion.

not sure documentatino is the answer, in fact, we should remove the status code if we don't have it.

from what I see in Envoy's docs, we can indeed get the status on the response phase.

```lua
function envoy_on_response(response_handle)
  -- Log response status code
  response_handle:logInfo("Status: "..response_handle:headers():get(":status"))
end

```

**Comment by tzuryby** [comment]
regarding the "xxx:decoded", two issues with that

 - once decoded, the decoded is the only value that matters. there is no need to store or process both. see, we do not have a signature for `OR%201%3D1` and one for `OR 1=1`

**Pull request closed without merging**
