### PR TITLE
Add release schedule docs

### PR DESCRIPTION
**Pull request by flaper87**

### CODE REVIEW

**Review by jdorfman — APPROVED** [review]
This is great. Will it replace ROADMAP?

**Comment by jdorfman** [comment]
@flaper87 in cases like this do you want me to merge or just wait for you to do it (either way is fine with me).

**Comment by flaper87** [comment]
> @flaper87 in cases like this do you want me to merge or just wait for you to do it (either way is fine with me).

It's fine if you merge it too. Generally, for a project like curiefense, I'd say it's ok to merge someone else's patches unless explicitly specified :D

**Comment by flaper87** [comment]
> This is great. Will it replace ROADMAP?

I think so. What do you think? Would there be value to have a roadma file in addition to this? Feature/bug wise we could use milestones as roadmap definition and have them documented in the RELEASE file.

**Comment by jdorfman** [comment]
> What do you think?

Remove it. =)

**Comment by flaper87** [comment]
> > What do you think?
> 
> Remove it. =)

https://github.com/curiefense/curiefense/pull/238

**Pull request merged**
