### PR TITLE
Rate Limit multiple thresholds support

### PR DESCRIPTION
**Pull request by Freakachoo**
According to issue https://github.com/curiefense/curiefense/issues/552 Rate Limit now supports multiple thresholds (action + limit).

# Changelog
- changed UI to support multiple thresholds
- removed `Threshold` field from `Security Policy` UI - because no normal way to show multiple, and anyway this will be removed in next changes (when Rate Limit Profiles will be added)
- added conversion functions to `confserver` utils, to support legacy v1 <-> v2, because v1 supported only one threshold per one rate limit. Added tests for the functions
- curieproxy adopted to use the new structure

Multiple thresholds:
image

Removed threshold in Security Profiles UI:
image

# TODO
Update docs!

### CODE REVIEW

**Review by bartavelle — DISMISSED** [review]
Rust part + lua tests LGTM!

**Comment by bartavelle** [comment]
The E2E tests were not updated though!

**Comment by Freakachoo** [comment]
> The E2E tests were not updated though!

Yeah just updated, thanx!

**Comment by jdorfman** [comment]
LGTM. Thanks for the screenshots.

**Comment by flaper87** [comment]
@Freakachoo let us know when this is ready for review :pray:

**Comment by Freakachoo** [comment]
@flaper87 @Ronyk1 is is ready for review!

**Review by flaper87 — APPROVED** [review]

**Pull request merged**
