### PR TITLE
Initial Grafana and Kibana Dashboards

### PR DESCRIPTION
**Pull request by Freakachoo**
As a part of issues https://github.com/curiefense/curiefense/issues/365, https://github.com/curiefense/curiefense/issues/364 and https://github.com/curiefense/curiefense/issues/7 adding a few dashboards for Grafana and Kibana to monitor users' activities.

Those dashboards are not final, these are just initial examples that show possibilities and gives inspiration for further changes. And we will change them accordingly to the usage of the system. So feel free to suggest changes, or create PRs by yourself.

Dashboards could be modified after new information will be added to the logs and some of the bugs will be solved and features added. A list of related issues:
https://github.com/curiefense/curiefense/issues/468
https://github.com/curiefense/curiefense/issues/437
https://github.com/curiefense/curiefense/issues/410
https://github.com/curiefense/curiefense/issues/408
https://github.com/curiefense/curiefense/issues/407
https://github.com/curiefense/curiefense/issues/406
https://github.com/curiefense/curiefense/issues/363
https://github.com/curiefense/curiefense/issues/100

# Dashboards:

### Grafana

Grafana dashboards were inspired and rebuilt from the ones created by @xavier-rbz 

#### Dashboard name: **Top 5 Activities**
image

A list of panels:
- Top Countries
- URL maps
- Methods
- Blocked Methods
- URIs
- Blocked URIs
- Blocking WAF IDs
- Blocking ACL IDs
- ASNs
- Tags

#### Dashboard name: **Traffic Overview**
image

A list of panels:
- Blocked vs Passed
- HTTP Status
- HTTP Origin Status
- Methods
- Requests
- Bandwidth

#### Dashboard name: **Activities**
image

A list of panels:
- Total requests
- Blocked vs Passed
- Bandwidth Bytes
- Status code
- ASNs
- Attacks Heat-map
- Rules Heat-map
- Block initiator
- Block Reasons by WAF
- Blocked by Tag Rule
- Blocked by Challange
- Blocked by Rate Limit
- Blocked by ACL
- Blocked by Flow Control
- URIs (top 50) _(table)_
- Tags (top 50) _(table)_
- IPs (top 50) _(table)_
- Countries _(table)_
- Requests per Country (top 15)

We have an issue to add Grafana dashboards to the community repository https://github.com/curiefense/curiefense/issues/24 but IMO it's too early. Opinioins?

### CODE REVIEW

**Comment by tzuryby** [comment]
@Freakachoo I do not see teh changes we discussed in our call on the screenshots, rather what you represented at the beginign of the call.

@yaniv, @maksim and @roei -- 

This is part of the _ATTACKS DASHBOARDS_ project.
Please make sure it is a great working tool to tackle with attacks.

**Comment by Freakachoo** [comment]
@tzuryby regarding tables for multiple objects (like IPs or Countries) - I have implemented, it is really more useful! But regarding the combined "blocked" panel - I've tried to achieve that, but for now without success. Not possible to easily combine different graphs. Was needed to spend more time on it, try Kibana plugins, etc. Decided to release it as it is, for now, to collect feedback and get back to it on the next iteration.

**Comment by flaper87** [comment]
@Freakachoo I believe this may require a rebase and some cleanup. Let me know if I can be of help here

**Comment by Freakachoo** [comment]
@flaper87 yes help me, please, if you may. I've tried many approaches and none worked fine enough. Would be glad to learn how to do this right. When I did rebase it just created a new commit on top, but all the rest stayed and DCO still blocked it.
I've setup gpg sign on my machine, so all next commits will be signed off correctly.

**Review by Aviv-Galmidi — APPROVED** [review]
I ran a general overview of the changes. It looks good to me

**Review by flaper87 — APPROVED** [review]

**Pull request merged**
