### PR TITLE
Include/exclude clauses for rate limiting now uses tags

### PR DESCRIPTION
**Pull request by bartavelle**
This commit modifies tests so that they conform to the new format.

However, it does not modify anything in the configuration server or the
UI!

Signed-off-by: Simon Marechal <bartavelle@gmail.com>

### CODE REVIEW

**Comment by bartavelle** [comment]
Looks like e2e tests need to be fixed as well ...

**Comment by bartavelle** [comment]
@xavier-rbz to be honest I really could use a hand here, either on how to setup local e2e testing, or in directly fixing the tests.

The issue is #462

**Comment by Aviv-Galmidi** [comment]
Relates to https://github.com/curiefense/curiefense/pull/467 and should be merged relatively together

**Comment by flaper87** [comment]
> @xavier-rbz to be honest I really could use a hand here, either on how to setup local e2e testing, or in directly fixing the tests.

Interestingly enough, the fluentd test passes which is almost the same as the minikube filebeat one but using fluentd instead of filebeat. The rest is all the same. It may have been a random failure. re-running tests now

**Review by flaper87 — APPROVED** [review]
The failures may not be related, although CI doesn't seem to be too stable lately.

**Comment by bartavelle** [comment]
They only run a subset of the tests, which is why they pass:

            pytest --log-level INFO --base-protected-url http://$IPPORT --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:30200/ --junit-xml pytest.xml -k 'not (test_ipv4 or test_wafsig or test_ratelimit_scope_ipv4_include or test_ratelimit_scope_ipv4_exclude or test_ratelimit_scope_country_include or test_ratelimit_scope_country_exclude or test_ratelimit_scope_company_include or test_ratelimit_scope_company_exclude or test_ratelimit_scope_provider_include or test_ratelimit_scope_provider_exclude or test_ratelimit_countby_ipv4 or test_ratelimit_countby_provider or test_ratelimit_countby_company or test_ratelimit_countby_country or test_ratelimit_event_ipv4 or test_ratelimit_event_ipv6 or test_ratelimit_event_provider or test_ratelimit_event_tag or test_ratelimit_event_company or test_ratelimit_event_country or test_logs or test_ip_asn or test_geo or test_ipv6 or test_ratelimit_scope_path_include or test_ratelimit_scope_path_include_exclud or test_ratelimit_scope_uri_include or test_ratelimit_scope_uri_include_exclud or test_ratelimit_scope_method_include or test_ratelimit_scope_method_exclude or test_ratelimit_scope_query_include or test_ratelimit_scope_query_exclude or test_ratelimit_scope_authority_include or test_ratelimit_scope_authority_exclude or test_ratelimit_countby_ipv6 or test_ratelimit_countby_uri or test_ratelimit_countby_path or test_ratelimit_countby_query or test_ratelimit_countby_method or test_ratelimit_countby_authority or test_ratelimit_event_uri or test_ratelimit_event_path or test_ratelimit_event_query or test_ratelimit_event_method or test_ratelimit_event_authority or test_ipv6 or test_country or test_asn or test_ratelimit_scope_include or test_ratelimit_scope_include_exclude or test_ratelimit_scope_exclude or test_ratelimit_countby_section or test_ratelimit_countby2_section or test_ratelimit_countby_2sections or test_ratelimit_event_section or test_length_overlong or test_length_short or test_count_few or test_count_toomany or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_allowlisted_value or test_non_allowlisted_value_restrict or test_non_allowlisted_value_norestrict_nowafmatch or test_non_allowlisted_value_norestrict_wafmatch or test_non_allowlisted_value_norestrict_wafmatch_excludesig or test_allowlisted_value or test_allowlisted_value or test_non_allowlisted_value_restrict or test_non_allowlisted_value_norestrict_nowafmatch or test_non_allowlisted_value_norestrict_wafmatch or test_non_allowlisted_value_norestrict_wafmatch_excludesig)' .

**Comment by shaisgv** [comment]
There are some inconsistencies and errors in the end to end tests.
1. For some cases we investigated, it is configuring an acl without defining a url map and checking that it is block in a url that is not mapped.
2. Also, it add an IP to the X_FORWARDED for header but this does not "fool"  curieproxy and it still tags the request as coming from localhost.

**Pull request merged**
