### PR TITLE
Optimize dockerfile

### PR DESCRIPTION
**Pull request by MicroOps-cn**
Reduce docker image size: 
```bash
# docker images|grep /curiefense-rustbuild
curiefense-rustbuild                     main                      f55925a8754f        3 hours ago         6MB
curiefense/curiefense-rustbuild-focal    main                      281447aac0f3        12 hours ago        1.85GB
curiefense/curiefense-rustbuild-bionic   main                      eb17f54229e8        12 hours ago        1.79GB
# docker images|grep curieproxy
curieproxy-istio                         1.13.2.0                  779e017a410d        3 hours ago         483MB
curieproxy-istio                         1.9.3.1                   23e2381946e3        5 hours ago         506MB
curiefense/curieproxy-istio              main                      1aa32f02f9f2        12 hours ago        764MB

```

### CODE REVIEW

**Comment by tzuryby** [comment]
@xavier-rbz please review

**Comment by MicroOps-cn** [comment]
> Hello, Would you mind rebasing your work on top of the `main` branch? There have been [changes](https://github.com/curiefense/curiefense/pull/820) to the `curiefense-rustbuild` image, whose Dockerfile no longer directly references libhyperscan4 or libhyperscan5 to maintain compability with both. This is what currently makes CI fail.

If libhyperscan4 is removed, the docker image will fail to compile in the last step (`RUN sh luatests/run.sh`). This step may be testing the generated curiefense.so, error log:
```log
Step 23/23 : RUN sh luatests/run.sh
 ---> Running in 6d6615884e8f
7:C 28 Apr 05:14:26.200 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
7:C 28 Apr 05:14:26.200 # Redis version=4.0.9, bits=64, commit=00000000, modified=0, pid=7, just started
7:C 28 Apr 05:14:26.200 # Configuration loaded
luajit: error loading module 'curiefense' from file '/usr/local/lib/lua/5.1/curiefense.so':
        libhs.so.4: cannot open shared object file: No such file or directory
stack traceback:
        [C]: at 0x56261125e0a0
        [C]: in function 'require'
        /home/builder/test.lua:2: in main chunk
        [C]: at 0x5626112081d0
Error response from daemon: The command '/bin/sh -c sh luatests/run.sh' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: curiefense/images/curiefense-rustbuild/Dockerfile': Can't retrieve image ID from build stream
```

**Comment by MicroOps-cn** [comment]
@xavier-rbz 
I optimized the Dockerfile of "curiefense-rustbuild" and should solve the libhyperscan compatibility problem you mentioned. I tested it locally using "bionic" and "focal", and found no problems. The output image was also tested on "curieproxy-istio", and found no other problems

After reading the log of this Ci failure, it doesn't look like it was caused by "curiefense-rustbuild"

**Review by xavier-rbz — APPROVED** [review]
I have fixed the issue & re-run CI, everything passes :)
Thanks for the PR.

**Pull request merged**
