### PR TITLE
Linters

### PR DESCRIPTION
**Pull request by Aviv-Galmidi**
Fixed bug preventing the ui from being initialized (1.2.19)
Added several linters (eslint, ts config, stylelint) with a Husky pre-commit hook to be run before every commit
Should block commits if any of these fail - hence they should never fail after this commit as they pass now
Currently missing type check for .vue files with "vti" (by vetur) as this plugin is in development

Also includes 1.2.19 ui changes from dev branch

### CODE REVIEW

**Comment by flaper87** [comment]
@Aviv-Galmidi may make sense to squash these commits so you only have one to sign (and to keep the history cleaner). What do you think?

**Comment by Aviv-Galmidi** [comment]
Tried resolving the DCO issue but ended up screwing the branch history, attempting to fix it

**Comment by flaper87** [comment]
> Tried resolving the DCO issue but ended up screwing the branch history, attempting to fix it 

I'd recommend squashing the commits in this PR ☺️

**Comment by Aviv-Galmidi** [comment]
> > Tried resolving the DCO issue but ended up screwing the branch history, attempting to fix it
> 
> I'd recommend squashing the commits in this PR ☺️

I tried that, and it asked me to resolve the rebase and resolve conflicts which leads me to the current state. I think I'll try taking all my changes into a new branch and add them in a single commit

**Comment by Aviv-Galmidi** [comment]
Re-opening the PR with the correct changes in a single commit

**Comment by Aviv-Galmidi** [comment]
new (cleaned) PR: https://github.com/curiefense/curiefense/pull/114

**Pull request closed without merging**
