### PR TITLE
Risk level management in WAF

### PR DESCRIPTION
**Pull request by bartavelle**
This implements #484

Signed-off-by: Simon Marechal <bartavelle@gmail.com>

### CODE REVIEW

**Review by Aviv-Galmidi — APPROVED** [review]

**Review by Aviv-Galmidi — APPROVED** [review]

**Comment by bartavelle** [comment]
This PR also introduces the decoding features.

**Review by Aviv-Galmidi — DISMISSED** [review]

**Comment by bartavelle** [comment]
So I rebased from your PR, all tests run, except the first which check in elasticsearch, so I guess there is something wrong with it:

```
Exiting: couldn't connect to any of the configured Elasticsearch hosts. Errors: [error connecting to Elasticsearch at http://elasticsearch:9200: Get "http://elasticsearch:9200": dial tcp 172.18.0.6:9200: connect: no route to host]
```

**Comment by bartavelle** [comment]
It is actually really annoying to test the new features as the e2e tests do not specify the WAF signatures :(

**Comment by bartavelle** [comment]
first test is basically random :/

**Comment by Aviv-Galmidi** [comment]
The e2e tests are acting up sometimes, but we're building new e2e infrastructure so that should be resolved in the near future hopefully

Either way, it seems like all the checks are passing now

**Review by Aviv-Galmidi — APPROVED** [review]

**Comment by bartavelle** [comment]
This had been merged!

**Pull request closed without merging**
