### PR TITLE
New e2e tests

### PR DESCRIPTION
**Pull request by bartavelle**
Replace the e2e tests so that it uses the lua test suite.

Currently needs:

  * support the flow control tests
  * add more things to test

### CODE REVIEW

**Review by tzuryby — APPROVED** [review]

**Comment by xavier-rbz** [comment]
This removes bitflip tests, most of which would be best done in the curieproxy unit tests. If we remove them from e2e tests, we won't see bugs coming from envoy, or bugs originating from way envoy interacts with lua+rust that might be different from what the lua+rust unit tests do.

**Comment by bartavelle** [comment]
> This removes bitflip tests, most of which would be best done in the curieproxy unit tests. If we remove them from e2e tests, we won't see bugs coming from envoy, or bugs originating from way envoy interacts with lua+rust that might be different from what the lua+rust unit tests do.

This is WIP, I would like to make it work like it worked before (with pytest), but checked if that was feasible with "real requests" first.
I would like to add the bitflip test, that part should not be too hard. However, I don't know how to make it behave like a pytest suite for now!

**Comment by bartavelle** [comment]
Managed to convert back to the pytest format! next: re-enable bit flip tests

**Comment by bartavelle** [comment]
Bit flip tests are back, but they take a long time to run. Compared to the rust compilation step, it's not that long, @xavier-rbz what do you think of adding a probability to run them to save some time?

**Review by tzuryby — APPROVED** [review]

**Comment by xavier-rbz** [comment]
> @xavier-rbz what do you think of adding a probability to run them to save some time?
Thanks for adding them back!
Running them for a random xx% of test runs would make tests undeterministic, I'm not convinced. To make tests faster, we could run these on a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) instead? Let's think about it.

**Pull request merged**
