### PR TITLE
Added support of risk level to WAF

### PR DESCRIPTION
**Pull request by Aviv-Galmidi**
* Add min risk level headers/cookies/arguments to WAF Policies - Relates to https://github.com/curiefense/curiefense/issues/484
* Add risk level attribute to WAF Rules - Relates to https://github.com/curiefense/curiefense/issues/484
* Add notes attribute to WAF Rules
* Fix issue where jest did not collect coverage from all files correctly
* Change eslint to better meet our standards
* Fix various lint issues according to the updated standards
* Change ResponseAction.vue to clear fields when switching action types - Closes https://github.com/curiefense/curiefense/issues/403
* Remove duplicated character from regex character class

Note: Needs work in the rust code as well which should be merged with a different PR

Signed-off-by: Aviv.Galmidi <AvivGalmidi@gmail.com>

### CODE REVIEW

**Review by denis-reblaze — COMMENTED** [review]
No need to add version?

**Comment by Aviv-Galmidi** [comment]
> No need to add version?

Fixed, do you have any further comments about the code?

**Comment by denis-reblaze** [comment]
> > No need to add version?
> 
> Fixed, do you have any further comments about the code?

Nope

**Comment by bartavelle** [comment]
Along with `args`, `headers` and `cookies`, there is are `path` parameters now.

It works just like there was a virtual "key" named `path`, where the value is the path. `names` and `regex` fields are parsed, and should be set to `[]`.

There is also a new `decoding` field which I believe is not specified yet, which controls which extra decoding steps should happen.

The related issue is #517

**Comment by bartavelle** [comment]
Actually I can work around it for now!

**Comment by bartavelle** [comment]
In the current iteration of #491 , I get green e2e tests locally, when I merge it with this PR (working branch https://github.com/bartavelle/curiefense/tree/bartavelle-latest). I randomly merged the UI code, as I do not need it to work.

**Comment by Aviv-Galmidi** [comment]
Closed as it's now part of https://github.com/curiefense/curiefense/pull/491

**Pull request closed without merging**
